collectors/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hosts, name='index'),
    path('hosts/', views.hosts, name='hosts'),
    path('host/<str:fqdn>/', views.host, name='host'),
    path('input/<str:software>/<str:name>/', views.input, name='input'),
    path('inputs/', views.inputs, name='inputs'),
    path('input_instances/', views.input_instances, name='input_instances'),
    path('softwares/', views.softwares, name='softwares'),
    path('software/<str:name>/', views.software, name='software'),
    path('ingest_telegraf/', views.ingest_telegraf, name='ingest_telegraf'),
]

footstick/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collectors.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

collectors/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.urls import reverse
import json


# Create your models here.
class Software(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=200, blank=True)
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('software', args=[str(self.name)])

    def __str__(self):
        return "%s" % (self.name)


class Input(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200, blank=True)
    software = models.ForeignKey(Software, on_delete=models.CASCADE)
    tags = TaggableManager()

    class Meta:
        unique_together = (('name', 'software'), )
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('input', args=[str(self.software), str(self.name)])

    def __str__(self):
        return "%s" % (self.name)


class Host(models.Model):
    fqdn = models.CharField(max_length=200, unique=True)
    inputs = models.ManyToManyField(Input, blank=True)
    tags = TaggableManager()

    class Meta:
        ordering = ['fqdn']

    def get_absolute_url(self):
        return reverse('host', args=[str(self.fqdn)])

    def __str__(self):
        return "%s" % (self.fqdn)


class InputInstance(models.Model):
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    configuration = models.CharField(max_length=254)
    s_input = models.ForeignKey(Input, on_delete=models.CASCADE)
    interval = models.DurationField()
    tags = TaggableManager()

    def parse_configuration(self):
        return json.loads(self.configuration)

    class Meta:
        unique_together = (('host', 'configuration', 's_input'), )
        ordering = ['s_input__name']

    def __str__(self):
        return "%s - %s - %s" % (self.host, self.configuration,
                                 self.s_input.name)

collectors/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Input, Software, Host, InputInstance
from datetime import timedelta
from django.template import loader
import sys
import json


def index(request):
    template = loader.get_template('collectors/index.html')
    return HttpResponse(template.render({}, request))


def hosts(request):
    template = loader.get_template('collectors/hosts.html')
    items = Host.objects.all()
    return HttpResponse(template.render({'items': items}, request))


def softwares(request):
    template = loader.get_template('collectors/softwares.html')
    items = Software.objects.all()
    return HttpResponse(template.render({'items': items}, request))


def software(request, name):
    item = Software.objects.get(name=name)
    template = loader.get_template('collectors/software.html')
    return HttpResponse(template.render({'item': item}, request))


def inputs(request):
    template = loader.get_template('collectors/inputs.html')
    items = Input.objects.all()
    return HttpResponse(template.render({'items': items}, request))


def input_instances(request):
    template = loader.get_template('collectors/input_instances.html')
    items = InputInstance.objects.all()
    return HttpResponse(template.render({'items': items}, request))


def input(request, software, name):
    item = Input.objects.get(software__name=software, name=name)
    template = loader.get_template('collectors/input.html')
    return HttpResponse(template.render({'item': item}, request))


def host(request, fqdn):
    item = Host.objects.get(fqdn=fqdn)
    template = loader.get_template('collectors/host.html')
    return HttpResponse(template.render({'item': item}, request))


@csrf_exempt
def ingest_telegraf(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        software, _ = Software.objects.get_or_create(name='telegraf')
        for item in data:

            # Parse the host here
            host, created = Host.objects.get_or_create(
                fqdn=item['metadata']['hostname'])
            if created:
                sys.stderr.write("Created Host: %s\n" % host)

            # Parse the Input
            s_input, created = Input.objects.get_or_create(
                name=item['plugin_type'], software=software)
            if created:
                sys.stderr.write("Created Input: %s\n" % s_input)

            # Parse the Input Instance
            input_instance, created = InputInstance.objects.get_or_create(
                host=host,
                s_input=s_input,
                configuration=item['plugin_config'],
                interval=timedelta(seconds=item['metadata']['interval']))
            if created:
                sys.stderr.write("Created: %s\n" % input_instance)

            sys.stderr.write("%s\n" % item)

        return HttpResponse("Done")

helpers/views.py
def application_vars(request):
    return {
        'application_title':
        "Metrics Collectors",
        'application_name':
        "Metrics Collectors",
        'secondary_nav_links': ['<a href="/logout">Logout</a>'],
        'nav_links': [
            {
                'class': 'nav-link',
                'link': '<a href="/hosts" class="nav-link">Hosts</a>'
            },
            {
                'class': 'nav-link',
                'link': '<a href="/inputs" class="nav-link">Inputs</a>'
            },
            {
                'class': 'nav-link',
                'link':
                '<a href="/input_instances" class="nav-link">Instances</a>'
            },
            {
                'class': 'nav-link',
                'link': '<a href="/softwares" class="nav-link">Software</a>'
            },
        ]
    }

collectors/templates/collectors/base.html
{% load staticfiles %}
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>
<body>
{% load bootstrap4 %}


{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% include 'collectors/nav.html' %}

    <div class="content container">
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
            {% block content %}
            {% endblock %}
    </div>
</body>

collectors/templates/collectors/host.html
{% extends 'ssiapp.html' %}
{% load humanize %}

{% block content %}
<div class="container" >
    <div class="lead">{{ item.fqdn }}</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Input</th>
                <th scope="col">Collector</th>
                <th scope="col">Interval</th>
                <th scope="col">Configuration Details</th>
            </tr>
        </thead>
        <tbody>
    {% for instance in item.inputinstance_set.all %}
            <tr>
                <td><a href="{{ instance.s_input.get_absolute_url }}">{{ instance.s_input }}</a></td>
                <td>{{ instance.s_input.software.name }}</td>
                <td>{{ instance.interval }}</td>
                <td><pre>{{ instance.configuration|pprint }}</pre></td>
            </tr>
    {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

collectors/templates/collectors/hosts.html
{% extends 'ssiapp.html' %}

{% block content %}
    <div class="lead">Hosts</div>
    <div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Host</th>
                <th scope="col">Input Instances</th>
            </tr>
        </thead>
        <tbody>
        {% for host in items %}
        <tr>
            <td><a href="{{ host.get_absolute_url }}">{{ host.fqdn }}</a></td>
            <td>{{ host.inputinstance_set.count }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

collectors/templates/collectors/index.html
{% extends 'collectors/base.html' %}

{% block content %}
<div class="container" >

    <div class="d-flex flex-wrap">
</p>Hi</p>
    </div>
</div>
{% endblock %}

collectors/templates/collectors/input.html
{% extends 'ssiapp.html' %}
{% load humanize %}

{% block content %}
<div class="container" >
    <div class="lead">{{ item.fqdn }}</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Host</th>
                <th scope="col">Interval</th>
                <th scope="col">Configuration Details</th>
            </tr>
        </thead>
        <tbody>
    {% for input in item.inputinstance_set.all %}
            <tr>
                <td><a href="{{ input.host.get_absolute_url }}">{{ input.host }}</a></td>
                <td>{{ input.interval }}</td>
                <td><pre>{{ input.configuration|pprint }}</pre></td>
            </tr>
    {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

collectors/templates/collectors/input_instances.html
{% extends 'ssiapp.html' %}

{% block content %}
    <div class="lead">Inputs</div>
    <div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Host</th>
                <th scope="col">Input</th>
                <th scope="col">Collector</th>
            </tr>
        </thead>
        <tbody>
        {% for item in items %}
        <tr>
            <td><a href="{{ item.host.get_absolute_url }}">{{ item.host }}</a></td>
            <td><a href="{{ item.s_input.get_absolute_url }}">{{ item.s_input.name }}</a></td>
            <td><a href="{{ item.s_input.software.get_absolute_url }}">{{ item.s_input.software.name }}</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

collectors/templates/collectors/inputs.html
{% extends 'ssiapp.html' %}

{% block content %}
    <div class="lead">Inputs</div>
    <div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Input</th>
                <th scope="col">Collector</th>
                <th scope="col">Input Instances</th>
            </tr>
        </thead>
        <tbody>
        {% for item in items %}
        <tr>
            <td><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
            <td><a href="{{ item.software.get_absolute_url }}">{{ item.software.name }}</a></td>
            <td>{{ item.inputinstance_set.count }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

collectors/templates/collectors/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Duke Metrics Inputs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/hosts">Hosts<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/inputs">Inputs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/inputinstances">Instances</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/graphql">API</a>
      </li>
    </ul>
    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->
  </div>
</nav>

collectors/templates/collectors/software.html
{% extends 'ssiapp.html' %}
{% load humanize %}

{% block content %}
<div class="container" >
    <div class="lead">{{ item.name }}</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Input</th>
                <th scope="col">Instances</th>
            </tr>
        </thead>
        <tbody>
    {% for input in item.input_set.all %}
            <tr>
                <td><a href="{{ input.get_absolute_url }}">{{ input }}</a></td>
                <td>{{ input.inputinstance_set.count }}</td>
            </tr>
    {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

collectors/templates/collectors/softwares.html
{% extends 'ssiapp.html' %}

{% block content %}
    <div class="lead">Software</div>
    <div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Software</th>
                <th scope="col">Inputs</th>
            </tr>
        </thead>
        <tbody>
        {% for item in items %}
        <tr>
            <td><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
            <td>{{ item.input_set.count }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}